### ISSUE TITLE
Reporting Bitcoin Core RPC error codes to Java

### ISSUE THREAD

**Issue by gsilvestri** [priiduneemre/btcd-cli4j#3] opened 2016-04-13 13:58 UTC
Randomly Bitcoin Core is not able to perform a requested action (sendFrom, sendMany, sendtoaddress, others...): the library report a generic error code:
"Error #1003002: The server responded with a non-OK (5xx) HTTP status code. Status line: HTTP/1.1 500 Internal Server Error, code=1003002"

**A way of getting the RPC error codes of the Bitcoin Core must be implemented.**

RPC error codes can be found here:
https://github.com/bitcoin/bitcoin/blob/master/src/rpc/protocol.h

**Comment by priiduneemre** [comment] 2016-04-13 14:51
Hi and thanks a lot for taking the time to report an issue!

The same problem was pointed out by another user in an email about a month ago. I have already fixed this in master (see commit fc1b6631eadd2e8566abba78b1cf93e64b0332f4). However, the bugfix hasn't been included in a binary release yet (due to my busy schedule lately). I'm hoping to implement the last 2 RPCs very soon and then prepare a new release.

In the meantime, feel free to clone the master branch.

Thanks again!

**Comment by priiduneemre** [comment] 2016-04-13 14:54
I'm closing this issue now (since it should already be fixed). If there are any more comments/questions, please feel free to write them down.

**Closed as completed by priiduneemre** 2016-04-13 14:54 UTC
Labels: Bug, Duplicate, JSON-RPC API, High priority

**Comment by gsilvestri** [comment] 2016-04-13 14:57
I was that user.
Question: why are you returning the response only for HTTP Status 500 and not returning the response for all the HTTP Status codes (from 400 to 599)?

I will test the implementation over the next months and let you know if the code is working as expected.
Thank You by then.

**Comment by priiduneemre** [comment] 2016-04-13 15:30
So essentially what this change does is that it lets internal server errors (HTTP code 500) bubble up through the HTTP layer and into the JSON-RPC layer. Other error conditions (such as "501 Not Implemented" or "505 HTTP Version Not Supported", for example) are irrelevant to Bitcoin and should be handled right in the HTTP layer (they might signal a faulty network connection or a timed out request, for example). 

As Bitcoin Core signals all user errors/software failures with "500 Internal Server Error", it is the only error code that needs to be analyzed further (that is why it is "returned", rather than throwing a fail-fast exception like for the other error codes). 

The unwanted behavior was caused by me forgetting to let 500s bubble through into the JSON-RPC layer for further inspection (incl. printing the protocols.h errors that you need).

I hope this answers your question.

**Comment by gsilvestri** [comment] 2016-04-13 15:37
This answered my question: thank You.

What I'm trying to understand now is if the JsonRpcClientImpl will throw a BitcoindException when Bitcoin Core return a HTTP status 500 (Internal Server Error).

Will the JsonRpcClientImpl throw a BitcoindException or will I have to check the response myself from JsonRpcClientImpl?

I'm asking this as **I cannot reproduce the issue**:  I have the library on a production environment (www.bitnow.it) and I don't know why this error is thrown:
- 90% of the times everything will go according to plans.
- 10% of the times I get the HTTP 500 "Internal server error"

I've tried:
1. Rebooting the server and the Bitcoin Core with -rescan option: that solved the issue once in testnet
2. Done the same thing on mainnet the error was not solved: I had to perform the transaction manually.
3. Another time in production the error disappeared as soon as I log into the server: the server was running in a remote location and as soon as I logged in was able to make the transaction.

When the sendFrom, sendToAddress, sendMany command is called all the proper checks are already been done (amount, wallet unlock, others...): so I'm 90% sure that the problem is somewhere else.

Knowing the exact RPC error will permits to fix this error.

**Will the JsonRpcClientImpl throw a BitcoindException or will I have to check the response myself from JsonRpcClientImpl in case of HTTP Status 500?**
- If the JsonRpcClientImpl will throw a BitcoindException (as working before) I will test this library in production without change on the server code.
- If the JsonRpcClientImpl has changed since than I will test it into testnet before going into production.

The problem is that **I cannot reproduce the issue**.

Thank You for your help.

EDIT: I had a hint writing this: I had the problem yesterday because the amount I was trying to send to did not had enough confirmations.
Amount I tried to send yesterday had 3 confirmations while I call the sendFrom() command with 6 options on confirmation.
Hope that explains also the other times I had this problem.

**Comment by priiduneemre** [comment] 2016-04-13 16:18
There have been no major changes to `JsonRpcClientImpl` in almost a year, so it should throw a `BitcoindException` just as before -- hopefully with additional information from Bitcoin Core this time. You don't have to to read/check the error manually from `JsonRpcClientImpl` (you couldn't, even if you wanted to). Look at the `checkResponse(..)` method starting on [line 131](https://github.com/priiduneemre/btcd-cli4j/blob/master/core/src/main/java/com/neemre/btcdcli4j/core/jsonrpc/client/JsonRpcClientImpl.java#L131) of `JsonRpcClientImpl` -- this is the code that will throw your error. It is called on [line 68](https://github.com/priiduneemre/btcd-cli4j/blob/master/core/src/main/java/com/neemre/btcdcli4j/core/jsonrpc/client/JsonRpcClientImpl.java#L68) of the same class, after checking that the JSON-RPC response is well-formed via `verifyResponse(..)` on [line 67](https://github.com/priiduneemre/btcd-cli4j/blob/master/core/src/main/java/com/neemre/btcdcli4j/core/jsonrpc/client/JsonRpcClientImpl.java#L67).

As for your specific case: I believe that insufficient confirmations might indeed be the problem, as you noted yourself. I can't think of any other good reason right now that would cause this kind of behavior (if failing to call `walletpassphrase` is out of the question).

EDIT: As to no up-to-date binary release being available atm -- you should be able to build `btcd-cli4j` just fine. IIRC, all you had to do is clone `master` from GitHub and run `mvn package`, which should give you the jars (I haven't built it in a while, but I'm pretty sure that was the only necessary step).

**Comment by gsilvestri** [comment] 2016-04-13 16:42
Thank You for quick response.

Will build the library on testnet and use it in there.

Will update the issue with the results.

Thank You.
